import React from "react";
import { useAddInvoice } from "@/hooks/invoice/invoice";
import { useForm, SubmitHandler } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { gmsInvoiceSchema } from "@/schemas/invoice/invoice";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { z } from "zod";
import { InvoiceStatus, InvoicePayload } from "@/types/index.d";
import { useSession } from "next-auth/react";

type FormInputs = z.infer<typeof gmsInvoiceSchema>;

export const AddInvoiceModal: React.FC<{
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
}> = ({ isOpen, onClose, onSuccess }) => {
  const { mutate: addInvoiceMutation, isPending } = useAddInvoice();
  const { data: session } = useSession();

  const { register, handleSubmit, reset, formState: { errors }, setValue } = useForm<FormInputs>({
    resolver: zodResolver(gmsInvoiceSchema),
    defaultValues: {
      user_id: session?.user?.id,
      gmsCustomerId: 1,
      status: InvoiceStatus.UNPAID,
      unit_consumed: 100,
      generatedByAgent: false,
      collected_by_agent_coin: false
    }
  });

  const onSubmit: SubmitHandler<FormInputs> = async (data) => {
    const submissionData = {
      ...data,
      id: session?.user?.id,
      generatedByAgent: Boolean(data.generatedByAgent),
      collected_by_agent_coin: Boolean(data.collected_by_agent_coin)
    };

    console.log('Submission payload:', submissionData);
    
    addInvoiceMutation(submissionData as InvoicePayload, {
      onSuccess: (response) => {
        if (response.success) {
          onClose();
          onSuccess();
          reset();
        }
      },
    });
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle>Add New Invoice</DialogTitle>
        </DialogHeader>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label htmlFor="gmsCustomerId">Customer ID</Label>
              <Input type="number" {...register("gmsCustomerId", { valueAsNumber: true })} />
              {errors.gmsCustomerId && <p className="text-red-500 text-xs">{errors.gmsCustomerId.message}</p>}
            </div>

            <div>
              <Label htmlFor="unit_consumed">Units Consumed</Label>
              <Input type="number" step="0.01" {...register("unit_consumed", { valueAsNumber: true })} />
              {errors.unit_consumed && <p className="text-red-500 text-xs">{errors.unit_consumed.message}</p>}
            </div>

            <div>
              <Label htmlFor="status">Status</Label>
              <select {...register("status")} className="w-full border rounded-md p-2">
                {Object.values(InvoiceStatus).map((status) => (
                  <option key={status} value={status}>
                    {status}
                  </option>
                ))}
              </select>
              {errors.status && <p className="text-red-500 text-xs">{errors.status.message}</p>}
            </div>

            <div className="flex items-center space-x-2">
              <Switch 
                id="generatedByAgent"
                onCheckedChange={(checked) => setValue("generatedByAgent", checked)}
                {...register("generatedByAgent")}
              />
              <Label htmlFor="generatedByAgent">Generated by Agent</Label>
            </div>

            <div className="flex items-center space-x-2">
              <Switch
                id="collected_by_agent_coin"
                onCheckedChange={(checked) => setValue("collected_by_agent_coin", checked)}
                {...register("collected_by_agent_coin")}
              />
              <Label htmlFor="collected_by_agent_coin">Collected by Agent Coin</Label>
            </div>
          </div>

          <div className="flex justify-end space-x-2">
            <Button type="button" variant="outline" onClick={onClose}>
              Cancel
            </Button>
            <Button type="submit" disabled={isPending}>
              {isPending ? "Adding..." : "Add Invoice"}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};