import React from "react";
import { useAddInvoice } from "@/hooks/invoice/invoice";
import { useForm, SubmitHandler } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { gmsInvoiceSchema } from "@/schemas/invoice/invoice";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { z } from "zod";
type FormInputs = z.infer<typeof gmsInvoiceSchema>;

export const AddInvoiceModal: React.FC<{
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
}> = ({ isOpen, onClose, onSuccess }) => {
  const { mutate: addInvoiceMutation, isPending } = useAddInvoice();
  
  const { register, handleSubmit, reset, formState: { errors } } = useForm<FormInputs>({
    resolver: zodResolver(gmsInvoiceSchema),
  });

  const onSubmit: SubmitHandler<FormInputs> = async (data) => {
    addInvoiceMutation(data, {
      onSuccess: (response) => {
        if (response.success) {
          onClose();
          onSuccess();
          reset();
        }
      },
    });
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle>Add New Invoice</DialogTitle>
        </DialogHeader>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label htmlFor="user_id">User ID</Label>
              <Input type="number" {...register("user_id", { valueAsNumber: true })} />
              {errors.user_id && <p className="text-red-500 text-xs">{errors.user_id.message}</p>}
            </div>
            
            <div>
              <Label htmlFor="gmsCustomerId">Customer ID</Label>
              <Input type="number" {...register("gmsCustomerId", { valueAsNumber: true })} />
              {errors.gmsCustomerId && <p className="text-red-500 text-xs">{errors.gmsCustomerId.message}</p>}
            </div>

            <div>
              <Label htmlFor="unit_consumed">Units Consumed</Label>
              <Input type="number" step="0.01" {...register("unit_consumed", { valueAsNumber: true })} />
              {errors.unit_consumed && <p className="text-red-500 text-xs">{errors.unit_consumed.message}</p>}
            </div>

            <div>
              <Label htmlFor="gas_unit_rate">Gas Unit Rate</Label>
              <Input type="number" step="0.01" {...register("gas_unit_rate", { valueAsNumber: true })} />
              {errors.gas_unit_rate && <p className="text-red-500 text-xs">{errors.gas_unit_rate.message}</p>}
            </div>

            <div>
              <Label htmlFor="bill_amount">Bill Amount</Label>
              <Input type="number" step="0.01" {...register("bill_amount", { valueAsNumber: true })} />
              {errors.bill_amount && <p className="text-red-500 text-xs">{errors.bill_amount.message}</p>}
            </div>

            <div className="flex items-center space-x-2">
              <Switch {...register("generatedByAgent")} />
              <Label htmlFor="generatedByAgent">Generated by Agent</Label>
            </div>
          </div>

          <div className="flex justify-end space-x-2">
            <Button type="button" variant="outline" onClick={onClose}>
              Cancel
            </Button>
            <Button type="submit" disabled={isPending}>
              {isPending ? "Adding..." : "Add Invoice"}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};